version: '3'

tasks:
  install:
    cmds:
      - docker build -t gym-unity-api .
      - docker rm -f gym-unity-api || true
      - docker run -d -p 5000:5000 --name gym-unity-api --network gymunity gym-unity-api
  
  initialise:
    cmds:
      - docker network create -d bridge gymunity || true
      - docker run --name gymunityapi-postgres -e POSTGRES_PASSWORD=postgres -p 6432:5432 --network gymunity --network-alias gymunity-postgres -d postgres
      - dotnet ef database update --project GymUnityApi.Endpoint
      - dotnet run --project GymUnityApi.Migration
  
  dbup:
    cmds:
      - dotnet run --project GymUnityApi.Migration
  
  start:
    dir: GymUnityApi.Endpoint
    cmds:
      - dotnet watch http